#!/usr/bin/env sh

echo "Validating commit message..."
npx --no -- commitlint --edit $1
COMMITLINT_EXIT_CODE=$?

if [ $COMMITLINT_EXIT_CODE -ne 0 ]; then
  echo "Commit message validation failed. Please fix your commit message."
  exit 1
fi

echo "Commit message validation passed."
